---
name: Bug Template
description: Raise tickets related to bugs found in the PD Curriculum. Keep in mind we are a small team of volunteers, so this might take up to 2 weeks to be dealt with PS: If you know of anyone wanting to volunteer for us, send them out way [#cyf-pd-syllabus])https://codeyourfuture.slack.com/archives/C01KMRERKS5)
title: "[Bug]: <descriptive title>"
assignees: "@me"
projects: "PD Syllabus"
body:
  - type: markdown
    attributes:
      value: >
        Make sure you fill in all the fields so your ticket is clear to everyone.
  - type: textarea
    id: link
    attributes:
      label: URL where you found the error
      description: Add the link of the curriculum page you found the error
      placeholder: https://cyf-curriculum.netlify.app/
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: What is wrong? 
      description: Explain what part of the curriculum is not correct: is the timing not adequate? Spelling mistakes? Content isn't clear?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What would you expect us to change?
      description: Suggest an adequate timing, spelling, content or write whatever makes it clear to us what should be amended.
    validations:
      required: true
  - type: dropdown
    id: priority
   attributes:
      label: What is the priority of this bug?
      multiple: false
      options:
        - Urgent
        - High
        - Medium
        - Low
    validations:
      required: true
